theme = "bento"
languageCode = "en-us"
baseurl = "https://bento-hugo-theme.netlify.app/"
title = "Bento"

author = "Leonardo Faria"
copyright = "MIT"

[taxonomies]
category = "categories"
tag = "tags"

# Better code higlighting
# via https://discourse.gohugo.io/t/pygmentscodefences-how-to-choose-themes/3842/3
pygmentsCodefences = true
pygmentsStyle = "vs"

# Integrations
googleAnalytics = "UA-XXXXXX-YY"
disqusShortname = "bento-hugo-theme"

# Hightlight theme
[markup.highlight]
  style = "github"

# Allow HTML rendering inside markdown
[markup.goldmark.renderer]
  unsafe = true

[params]
  # Show intro in the home page (with headline and description)
  intro = true
  headline = "This is a headline"
  description = "A minimalist theme for Hugo, build with Tailwind CSS."

  # Copyright note in the footer
  copyright = "Copyright Â© 2020 Someone"

  # Image in the homepage. You can setup a different image for social media
  cover = "images/vancouver.jpg"
  ogImage = "images/og_image.jpg"

  # Social media usernames
  github = "XXXX"
  twitter = "XXXX"
  linkedin = "https://linkedin.com/in/XXXX"
  email = "email@xxxx.com"

  # Avatar (shown in the homepage)
  avatar = "images/avatar.jpg"
  # Bio is shown in the end of posts
  authorBio = "Bento is a doggo who likes to code. Follow him on <a href='#'>Twitter</a>"

# Items in the top menu
[menu]
  [[menu.main]]
      name = "About"
      url = "/about"
      weight = 1

  [[menu.main]]
      name = "Archives"
      url = "/archives"
      weight = 1

  [[menu.main]]
      name = "Source code"
      url = "https://github.com/leonardofaria/bento"
      weight = 1
